all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: config/zuul.d/_jobs-base.yaml@master#3>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#46>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#60>'
      attempts: 1
      branch: master
      build: a5d2d1b03c314505891db09f66d784b6
      buildset: 4851561a0726483dbc6cc706b8fb8ec1
      change_url: https://sftests.com/r/plugins/gitiles/config/+/911c19a23b1fca0b9a15f6678eecb04b727ed578^!/
      child_jobs: []
      event_id: 2bfcc4e09ad84f79b8c26530b474eb5f
      executor:
        hostname: managesf.sftests.com
        inventory_file: /var/lib/zuul/builds/a5d2d1b03c314505891db09f66d784b6/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/a5d2d1b03c314505891db09f66d784b6/work/logs
        result_data_file: /var/lib/zuul/builds/a5d2d1b03c314505891db09f66d784b6/work/results.json
        src_root: /var/lib/zuul/builds/a5d2d1b03c314505891db09f66d784b6/work/src
        work_root: /var/lib/zuul/builds/a5d2d1b03c314505891db09f66d784b6/work
      items:
      - branch: master
        project:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          name: config
          short_name: config
          src_dir: src/sftests.com/config
      job: config-update
      jobtags: []
      newrev: 911c19a23b1fca0b9a15f6678eecb04b727ed578
      oldrev: 0edd640c69960fb2e7c8e49641a8d5d5620ab50d
      pipeline: post
      playbook_context:
        playbook_projects:
          trusted/project_0/sftests.com/config:
            canonical_name: sftests.com/config
            checkout: master
            commit: 911c19a23b1fca0b9a15f6678eecb04b727ed578
          trusted/project_1/sftests.com/sf-jobs:
            canonical_name: sftests.com/sf-jobs
            checkout: master
            commit: 176d24817993b9975ffb4b87a6e1825764ceeeb9
          trusted/project_2/sftests.com/zuul-jobs:
            canonical_name: sftests.com/zuul-jobs
            checkout: master
            commit: 19243afbec6b3980b38a1feffa89a74032becb8c
        playbooks:
        - path: trusted/project_0/sftests.com/config/playbooks/config/config-update.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/config
            link_target: trusted/project_0/sftests.com/config
            role_path: ansible/playbook_0/role_0/config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/sf-jobs
            link_target: trusted/project_1/sftests.com/sf-jobs
            role_path: ansible/playbook_0/role_1/sf-jobs/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_2/zuul-jobs
            link_target: trusted/project_2/sftests.com/zuul-jobs
            role_path: ansible/playbook_0/role_2/zuul-jobs/roles
      post_review: true
      project:
        canonical_hostname: sftests.com
        canonical_name: sftests.com/config
        name: config
        short_name: config
        src_dir: src/sftests.com/config
      projects:
        sftests.com/config:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          checkout: master
          checkout_description: zuul branch
          commit: 911c19a23b1fca0b9a15f6678eecb04b727ed578
          name: config
          required: false
          short_name: config
          src_dir: src/sftests.com/config
      ref: refs/heads/master
      resources: {}
      tenant: local
      timeout: 1800
      voting: true
    zuul_use_fetch_output: true
