all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: config/zuul.d/_jobs-base.yaml@master#3>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#46>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#60>'
      attempts: 1
      branch: master
      build: c01a4897092442b09decdfe565a5955b
      buildset: fb16339fb4ba4a66b053ed93d177ec94
      change_url: https://sftests.com/r/plugins/gitiles/config/+/0edd640c69960fb2e7c8e49641a8d5d5620ab50d^!/
      child_jobs: []
      event_id: 1af8d64533414ff4916c4c751bdca6a3
      executor:
        hostname: managesf.sftests.com
        inventory_file: /var/lib/zuul/builds/c01a4897092442b09decdfe565a5955b/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/c01a4897092442b09decdfe565a5955b/work/logs
        result_data_file: /var/lib/zuul/builds/c01a4897092442b09decdfe565a5955b/work/results.json
        src_root: /var/lib/zuul/builds/c01a4897092442b09decdfe565a5955b/work/src
        work_root: /var/lib/zuul/builds/c01a4897092442b09decdfe565a5955b/work
      items:
      - branch: master
        project:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          name: config
          short_name: config
          src_dir: src/sftests.com/config
      job: config-update
      jobtags: []
      newrev: 0edd640c69960fb2e7c8e49641a8d5d5620ab50d
      oldrev: 1568dbd648eb4d69449921726956ae687c250078
      pipeline: post
      playbook_context:
        playbook_projects:
          trusted/project_0/sftests.com/config:
            canonical_name: sftests.com/config
            checkout: master
            commit: 0edd640c69960fb2e7c8e49641a8d5d5620ab50d
          trusted/project_1/sftests.com/sf-jobs:
            canonical_name: sftests.com/sf-jobs
            checkout: master
            commit: 176d24817993b9975ffb4b87a6e1825764ceeeb9
          trusted/project_2/sftests.com/zuul-jobs:
            canonical_name: sftests.com/zuul-jobs
            checkout: master
            commit: 19243afbec6b3980b38a1feffa89a74032becb8c
        playbooks:
        - path: trusted/project_0/sftests.com/config/playbooks/config/config-update.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/config
            link_target: trusted/project_0/sftests.com/config
            role_path: ansible/playbook_0/role_0/config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/sf-jobs
            link_target: trusted/project_1/sftests.com/sf-jobs
            role_path: ansible/playbook_0/role_1/sf-jobs/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_2/zuul-jobs
            link_target: trusted/project_2/sftests.com/zuul-jobs
            role_path: ansible/playbook_0/role_2/zuul-jobs/roles
      post_review: true
      project:
        canonical_hostname: sftests.com
        canonical_name: sftests.com/config
        name: config
        short_name: config
        src_dir: src/sftests.com/config
      projects:
        sftests.com/config:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          checkout: master
          checkout_description: zuul branch
          commit: 0edd640c69960fb2e7c8e49641a8d5d5620ab50d
          name: config
          required: false
          short_name: config
          src_dir: src/sftests.com/config
      ref: refs/heads/master
      resources: {}
      tenant: local
      timeout: 1800
      voting: true
    zuul_use_fetch_output: true
