all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: config/zuul.d/_jobs-base.yaml@master#3>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#46>'
      - '<Job config-update branches: None source: config/zuul.d/_jobs-base.yaml@master#60>'
      attempts: 1
      branch: master
      build: ae9b8bd8ff2144879b23621cda5b2b47
      buildset: 51e4c802949343879283e2a5bdd92bde
      change_url: https://sftests.com/r/plugins/gitiles/config/+/c9f635841fb4fe304d3f82772a957d1edb1c634f^!/
      child_jobs: []
      event_id: 4b8f7de563b24d97be5600d337dffb77
      executor:
        hostname: managesf.sftests.com
        inventory_file: /var/lib/zuul/builds/ae9b8bd8ff2144879b23621cda5b2b47/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/ae9b8bd8ff2144879b23621cda5b2b47/work/logs
        result_data_file: /var/lib/zuul/builds/ae9b8bd8ff2144879b23621cda5b2b47/work/results.json
        src_root: /var/lib/zuul/builds/ae9b8bd8ff2144879b23621cda5b2b47/work/src
        work_root: /var/lib/zuul/builds/ae9b8bd8ff2144879b23621cda5b2b47/work
      items:
      - branch: master
        project:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          name: config
          short_name: config
          src_dir: src/sftests.com/config
      job: config-update
      jobtags: []
      newrev: c9f635841fb4fe304d3f82772a957d1edb1c634f
      oldrev: 911c19a23b1fca0b9a15f6678eecb04b727ed578
      pipeline: post
      playbook_context:
        playbook_projects:
          trusted/project_0/sftests.com/config:
            canonical_name: sftests.com/config
            checkout: master
            commit: c9f635841fb4fe304d3f82772a957d1edb1c634f
          trusted/project_1/sftests.com/sf-jobs:
            canonical_name: sftests.com/sf-jobs
            checkout: master
            commit: 176d24817993b9975ffb4b87a6e1825764ceeeb9
          trusted/project_2/sftests.com/zuul-jobs:
            canonical_name: sftests.com/zuul-jobs
            checkout: master
            commit: 19243afbec6b3980b38a1feffa89a74032becb8c
        playbooks:
        - path: trusted/project_0/sftests.com/config/playbooks/config/config-update.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/config
            link_target: trusted/project_0/sftests.com/config
            role_path: ansible/playbook_0/role_0/config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/sf-jobs
            link_target: trusted/project_1/sftests.com/sf-jobs
            role_path: ansible/playbook_0/role_1/sf-jobs/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_2/zuul-jobs
            link_target: trusted/project_2/sftests.com/zuul-jobs
            role_path: ansible/playbook_0/role_2/zuul-jobs/roles
      post_review: true
      project:
        canonical_hostname: sftests.com
        canonical_name: sftests.com/config
        name: config
        short_name: config
        src_dir: src/sftests.com/config
      projects:
        sftests.com/config:
          canonical_hostname: sftests.com
          canonical_name: sftests.com/config
          checkout: master
          checkout_description: zuul branch
          commit: c9f635841fb4fe304d3f82772a957d1edb1c634f
          name: config
          required: false
          short_name: config
          src_dir: src/sftests.com/config
      ref: refs/heads/master
      resources: {}
      tenant: local
      timeout: 1800
      voting: true
    zuul_use_fetch_output: true
